export const OAUTH = "OAUTH";
export const POPULATE_PROFILE_LOADING = "POPULATE_PROFILE_LOADING";
export const POPULATE_PROFILE = "POPULATE_PROFILE";
export const POPULATE_PROFILE_ERROR = "POPULATE_PROFILE_ERROR";

